global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'simple-inventory'
    static_configs:
      ## - targets: ['host.docker.internal:8080'] ## Docker
      - targets: ['host.containers.internal:8080'] ## Podman
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s